### ISSUE TITLE
Build error regarding js import

### ISSUE THREAD

**Issue by nlfiedler** [billperegoy/elm-validations#8]
After installing version 1.0.2 and building using `node`, I get the following error:

```shell
$ LOGGY_STACKS=1 node node_modules/.bin/brunch build
15:09:11 - error: Processing of elm/elm-stuff/packages/billperegoy/elm-form-validations/1.0.2/bootstrap-3.3.7-dist/js/npm.js failed. Error: Could not load module '../../js/alert.js' from '/Users/nfiedler/projects/tanuki/apps/tanuki_web/assets/elm/elm-stuff/packages/billperegoy/elm-form-validations/1.0.2/bootstrap-3.3.7-dist/js'. Make sure the file actually exists.
  at friendlyRequireError (/Users/nfiedler/projects/tanuki/apps/tanuki_web/assets/node_modules/deppack/lib/resolve.js:69:9)
  at browserResolve (/Users/nfiedler/projects/tanuki/apps/tanuki_web/assets/node_modules/deppack/lib/resolve.js:90:17)
  at /Users/nfiedler/projects/tanuki/apps/tanuki_web/assets/node_modules/browser-resolve/index.js:265:24
  at /Users/nfiedler/projects/tanuki/apps/tanuki_web/assets/node_modules/resolve/lib/async.js:55:18
  at load (/Users/nfiedler/projects/tanuki/apps/tanuki_web/assets/node_modules/resolve/lib/async.js:69:43)
  at onex (/Users/nfiedler/projects/tanuki/apps/tanuki_web/assets/node_modules/resolve/lib/async.js:92:31)
  at /Users/nfiedler/projects/tanuki/apps/tanuki_web/assets/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by billperegoy** [comment]
I'll look into this. It seems odd that there is a reference to bootstrap inside this package. I was using bootstrap for testing the library but wasn't expecting it to be included in the package. That seems wrong. Thanks for pointing this out!
